version: "3.8"

services:
    ruby:
        build: ./ruby
        volumes:
            - ${CONTAINER_PATH}/${SITE_DIR}:/usr/src/app
        ports:
            - 3000:3000
        networks:
            - ${NETWORK}
        restart: "no"

networks:
    ruby_network:
        name: ${NETWORK}
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}

#volumes:
    #app-v#olume:
        #driver: local
#        mountpoint: ${CONTAINER_PATH}/${SITE_DIR}