version: "3.8"

services:
    ruby:
        build:
            context: "./ruby"
            dockerfile: Dockerfile
            args:
                - APP_USER_UID=${APP_USER_UID}
                - APP_GROUP_GID=${APP_GROUP_GID}
        command: bash -c "rm -f /tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - app-volume:/usr/src/app
        ports:
            - "3000:3000"
        networks:
            - ${NETWORK}
        restart: "no"
        #tty: true
        #stdin_open: true

networks:
    ruby_network:
        name: ${NETWORK}
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}

volumes:
    app-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./${SITE_DIR}